### STAT 610
### Final Project
### TO RUN: testthat::test_dir('.') 
### by Jiongran Wang & Yuanyuan luan 

# load package functions and functions we want to test
library(testthat)
source('MML_Function .R')

context("Check Markov Model for Lauguange")

## Try with a short sentence
sen.test = "Markov model is tedious but it is also a great model"

words = toupper(strsplit(sen.test," ")[[1]])
words

### test to prove the list generated by MMML() is right
test_that("word Markov followed with word model",{
  expect_equivalent("MODEL", MML(words)[["MARKOV"]])
})

test_that("word is followed with word tedious and also",{
  expect_equivalent(c("TEDIOUS", "ALSO"), MML(words)[["IS"]])
})

## test to prove that every unique word has been used as a name of vector in the MML list
test_that("number of unique words is the same as the number of names of MML list",{
  expect_equal(length(unique(words)), length(names(MML(words))))
})
